In [ ]:
from google.colab import files
uploaded = files.upload()

Saving hindi_15.tsv to hindi_15.tsv


In [ ]:
import pandas as pd
import re

def clean_text(text):
    # remove URLs, mentions, and hashtags
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\S+', '', text)
    text = re.sub(r'#\S+', '', text)
    # remove non-alphanumeric characters
   # text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # convert to lowercase
  #  text = text.lower()
    return text



In [ ]:
import pandas as pd

# read in the data as a Pandas DataFrame
df = pd.read_csv('hindi_15.tsv', sep='\t', header=None, names=['text_id', 'text', 'task_1', 'task_2', 'task_3'])

# clean the dataset
df['text'] = df['text'].apply(clean_text)

# create a new DataFrame with just the text_id and text columns
df_text = df[['text_id', 'text']].copy()

# convert the task_1, task_2, and task_3 columns to 0s and 1s
df_tasks = pd.get_dummies(df[['task_1', 'task_2', 'task_3']])

# concatenate the text and task DataFrames
df = pd.concat([df_text, df_tasks], axis=1)

# print the new DataFrame



In [ ]:
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_1_task_1  task_2_NONE  task_2_PRFN  \
0           0           0              1            0            0   
1           0           1              0            1            0   
2           1           0              0            0            1   
3           1           0              0            0            1   
4           0           1              0            1            0   

   task_2_task_2  task_3_NONE  task_3_TIN  task_3_UNT  task_3_task_3  
0              1            0           0           0              1  
1              0            1           0           0              0  
2              0            0           0           1              0  
3              0            0           1           0              0  
4              0            1           0           0              0

In [ ]:
!pip install mtranslate
import random
import time
import mtranslate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for mtranslate: filename=mtranslate-1.8-py3-none-any.whl size=3671 sha256=feb6808663bb2d4a50f3d1f30b903362d4432cabc761951941105f80d6865994
  Stored in directory: /root/.cache/pip/wheels/c2/04/15/d7654c2c4a9a52e09922967593f3278fed66059be65ca671ea
Successfully built mtranslate


In [ ]:

def code_mix(text, cmi):
    # translate the text to English
    eng_text = mtranslate.translate(text, 'en')
    # split the English text into words
    eng_words = eng_text.split()
    # replace some of the English words with Hindi words
    num_hindi_words = int(cmi * len(eng_words))
    hindi_words = []
    for i in range(num_hindi_words):
        # translate the current English word to Hindi
        try:
            hindi_word = mtranslate.translate(eng_words[i], 'hi')
        except ValueError:
            continue  # skip this word if translation fails
        hindi_words.append(hindi_word)
        eng_words[eng_words.index(eng_words[i])] = hindi_word
        # add a delay of 1 second between translation requests
        time.sleep(1)
    # join the words back into a sentence
    code_mixed_text = ' '.join(eng_words)
    print(code_mixed_text)
    return code_mixed_text

In [ ]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
df = df.drop(columns=['task_2_NONE','task_3_NONE',])

In [ ]:
df = df.drop(columns=['task_1_task_1','task_2_task_2',"task_3_task_3"])

In [ ]:
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  
0           0           0            0           0           0  
1           0           1            0           0           0  
2           1           0            1           0           1  
3           1           0            1           1           0  
4           0           1            0           0           0

In [ ]:
df.drop(index=0)


text_id                                               text  \
1   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
5   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
6   hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
7   hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
8   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
9   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12   hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
13  hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
14  hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  
1            0           1            0           0           0  
2            1           0            1           0           1  
3            1           0            1           1           0  
4            0           1            0           0           0  
5            0           1            0           0           0  
6            0           1            0           0           0  
7            0           1            0           0           0  
8            0           1            0           0           0  
9            0           1            0           0           0  
10           0           1            0           0           0  
11           0           1            0           0           0  
12           0           1            0           0           0  
13           0           1            0           0           0  
14           0           1            0           0           0  
15           0           1            0           0           0

In [ ]:
def code_mix(text, cmi):
    # translate the text to English
    eng_text = mtranslate.translate(text, 'en')
    # split the English text into words
    eng_words = eng_text.split()
    # replace some of the English words with Hindi words
    num_hindi_words = int(cmi * len(eng_words))
    hindi_words = []
    for i in range(num_hindi_words):
        # translate the current English word to Hindi
        try:
            hindi_word = mtranslate.translate(eng_words[i], 'hi')
        except ValueError:
            continue  # skip this word if translation fails
        hindi_words.append(hindi_word)
        eng_words[eng_words.index(eng_words[i])] = hindi_word
        # add a delay of 1 second between translation requests
        time.sleep(1)
    # join the words back into a sentence
    code_mixed_text = ' '.join(eng_words)
    return code_mixed_text

In [ ]:
# create code mixed data for different CMI values
cmin_vals = [0.1,0.3,0.5]
#code_mix("बांग्लादेश की शानदार वापसी, भारत को 314 रन पर रोका #INDvBAN #CWC19",0.1)
for cmi in cmin_vals:
    df[f'text_code_mixed_{cmi}'] = df['text'].apply(lambda x: code_mix(x, cmi))
    print(df.head())

         text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  \
0           0           0            0           0           0   
1           0           1            0           0           0   
2           1           0            1           0           1   
3           1           0            1           1           0   
4           0           1            0           0           0   

                                 text_code_mixed_0.1  
0                                               text  
1  Great comeback of Bangladesh, stopped India fo...  
2  सब लोग i

In [ ]:
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  \
0           0           0            0           0           0   
1           0           1            0           0           0   
2           1           0            1           0           1   
3           1           0            1           1           0   
4           0           1            0           0           0   

                                 text_code_mixed_0.1  \
0                                               text   
1  Great comeback of Bangladesh, stopped India fo...   
2  सब लोग is busy watching Randi dance, as soon a...   
3  वहाँ है केवल ए कमी का shoes for bastards like ...   
4  बी जे पी MLA Akash Vijayvargiya released from ...   

                                 text_code_mixed_0.3  \
0                                               text   
1  महान वापस लौटें of Bangladesh, stopped India f...   
2  सब लोग है व्यस्त देख रहे Randi dance, as soon ...   
3  वहाँ है केवल ए कमी का जूते के लिए कमीनों पसंद ...   
4  बी जे पी विधायक आकाश Vijayvargiya मुक्त from j...   

                                 text_code_mixed_0.5  
0                                               text  
1  महान वापस लौटें का बांग्लादेश, stopped India f...  
2  सब लोग है व्यस्त देख रहे रैंडी नृत्य, जैसा जल्...  
3  वहाँ है केवल ए कमी का जूते के लिए कमीनों पसंद ...  
4  बी जे पी विधायक आकाश Vijayvargiya मुक्त से जेल...

In [ ]:
pip install Keras-Preprocessing


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.8 MB/s eta 0:00:00


In [ ]:
!pip install transformers
import pandas as pd
import numpy as np
import tensorflow as tf
import torch
import keras
from torch.nn import BCEWithLogitsLoss, BCELoss
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from keras_preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report, confusion_matrix, multilabel_confusion_matrix, f1_score, accuracy_score
import pickle
from transformers import *
from tqdm import tqdm, trange
from ast import literal_eval

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 62.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 27.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 75.8 MB/s eta 0:00:00


/usr/local/lib/python3.10/dist-packages/transformers/generation_utils.py:24: FutureWarning: Importing `GenerationMixin` from `src/transformers/generation_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import GenerationMixin` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation_tf_utils.py:24: FutureWarning: Importing `TFGenerationMixin` from `src/transformers/generation_tf_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import TFGenerationMixin` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation_flax_utils.py:24: FutureWarning: Importing `FlaxGenerationMixin` from `src/transformers/generation_flax_utils.py` is deprecated and will be removed in Transformers v5. Import as `from transformers import FlaxGenerationMixin` instead.
  warnings.warn(
Xformers is not installed correctly. If you want to use memorry_efficient_attenti

In [ ]:
print('Unique comments: ', df.text.nunique() == df.shape[0])
print('Null values: ', df.isnull().values.any())
# df[df.isna().any(axis=1)]

Unique comments:  True
Null values:  False


In [ ]:
df1 = df.sample(frac=1).reset_index(drop=True) #shuffle rows


In [ ]:
cols = df.columns[0:7]
label_cols = list(cols[2:])
num_labels = len(label_cols)
print('Label columns: ', label_cols)


Label columns:  ['task_1_HOF', 'task_1_NOT', 'task_2_PRFN', 'task_3_TIN', 'task_3_UNT']


In [ ]:
df['one_hot_labels'] = list(df[label_cols].values)
df.head()

text_id                                               text  \
0        text_id                                               text   
1  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2  hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3   hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4  hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   

   task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  \
0           0           0            0           0           0   
1           0           1            0           0           0   
2           1           0            1           0           1   
3           1           0            1           1           0   
4           0           1            0           0           0   

                                 text_code_mixed_0.1  \
0                                               text   
1  Great comeback of Bangladesh, stopped India fo...   
2  सब लोग is busy watching Randi dance, as soon a...   
3  वहाँ है केवल ए कमी का shoes for bastards like ...   
4  बी जे पी MLA Akash Vijayvargiya released from ...   

                                 text_code_mixed_0.3  \
0                                               text   
1  महान वापस लौटें of Bangladesh, stopped India f...   
2  सब लोग है व्यस्त देख रहे Randi dance, as soon ...   
3  वहाँ है केवल ए कमी का जूते के लिए कमीनों पसंद ...   
4  बी जे पी विधायक आकाश Vijayvargiya मुक्त from j...   

                                 text_code_mixed_0.5   one_hot_labels  
0                                               text  [0, 0, 0, 0, 0]  
1  महान वापस लौटें का बांग्लादेश, stopped India f...  [0, 1, 0, 0, 0]  
2  सब लोग है व्यस्त देख रहे रैंडी नृत्य, जैसा जल्...  [1, 0, 1, 0, 1]  
3  वहाँ है केवल ए कमी का जूते के लिए कमीनों पसंद ...  [1, 0, 1, 1, 0]  
4  बी जे पी विधायक आकाश Vijayvargiya मुक्त से जेल...  [0, 1, 0, 0, 0]

In [ ]:
df1 = df.sample(frac=1).reset_index(drop=True) #shuffle rows


In [ ]:
df1

text_id                                               text  \
0    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
1   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
2   hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
3   hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
4         text_id                                               text   
5   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
6   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
7   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
8   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
9    hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
12  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   
13  hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
14  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
15  hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   

    task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  \
0            1           0            1           1           0   
1            0           1            0           0           0   
2            0           1            0           0           0   
3            0           1            0           0           0   
4            0           0            0           0           0   
5            1           0            1           0           1   
6            0           1            0           0           0   
7            0           1            0           0           0   
8            0           1            0           0           0   
9            0           1            0           0           0   
10           0           1            0           0           0   
11           0           1            0           0           0   
12           0           1            0           0           0   
13           0           1            0           0           0   
14           0           1            0           0           0   
15           0           1            0           0           0   

                                  text_code_mixed_0.1  \
0   वहाँ है केवल ए कमी का shoes for bastards like ...   
1   वहाँ हैं great powers, there is happiness on a...   
2   कुछ लोग sitting on religious positions conside...   
3   डॉ। मुखर्जी लड़ा to end permit raj considering...   
4                                                text   
5   सब लोग is busy watching Randi dance, as soon a...   
6   5 लाख मुसलमानों come to Ajmer's Dargah in Urs,...   
7   बी जे पी MLA Akash Vijayvargiya released from ...   
8   Chamki fever: RJD's performance in the assembl...   
9   वे WHO वादा करना atrocities in the name of cow...   
10  मंत्र of 'Jai Sri Ram' as Owaisi takes oath: A...   
11  Great comeback of Bangladesh, stopped India fo...   
12   सिक्का है kept the boom of love ~ yes but has...   
13  अहमद का dad:-- beta aaj teri mammy kyu nahi ba...   
14  वहाँ इच्छा होना dance..! There will be music.....   
15  लोग are facing a lot of problems due to rain i...   

                                  text_code_mixed_0.3  \
0   वहाँ है केवल ए कमी का जूते के लिए कमीनों पसंद ...   
1   वहाँ हैं महान शक्तियां, वहाँ है ख़ुशी on all s...   
2   कुछ लोग बैठक पर धार्मिक पदों विचार करना themse...   
3   डॉ। मुखर्जी लड़ा को अंत आज्ञा देना राज मानते ह...   
4                                                text   
5   सब लोग है व्यस्त देख रहे Randi dance, as soon ...   
6   5 लाख मुसलमानों आना को अजमेर का दरगाह में उर्स...   
7   बी जे पी विधायक आकाश Vijayvargiya मुक्त from j...   
8   Chamki बुखार: राजद के प्रदर्शन in the assembly...   
9   वे WHO वादा करना अत्याचार में  नाम का गाय, you...   
10  मंत्र का 'जय श्री Ram' as Owaisi takes oath:

In [ ]:
labels = list(df.one_hot_labels.values)
comments = list(df.text.values)

In [ ]:
labels

[array([0, 0, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([1, 0, 1, 0, 1], dtype=uint8),
 array([1, 0, 1, 1, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8),
 array([0, 1, 0, 0, 0], dtype=uint8)]

In [ ]:
# Importing stock ml libraries
import numpy as np
import pandas as pd
from sklearn import metrics
import transformers
import torch
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from transformers import BertTokenizer, BertModel, BertConfig

In [ ]:
df.rename(columns = {'text':'comment_text',
                              'one_hot_labels':'list'}, inplace = True)

In [ ]:
df=df.iloc[1:, :]

In [ ]:
df

text_id                                       comment_text  \
1   hasoc_hi_5556  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...   
2   hasoc_hi_5648  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...   
3    hasoc_hi_164  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...   
4   hasoc_hi_3530  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...   
5   hasoc_hi_5206  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...   
6   hasoc_hi_5121  मुंबई में बारिश से लोगों को काफी समस्या हो रही है   
7   hasoc_hi_7142  Ahmed's dad:-- beta aaj teri mammy kyu nahi ba...   
8   hasoc_hi_4321  5 लाख मुसलमान उर्स में, अजमेर की दरगाह पर आते ...   
9   hasoc_hi_4674  Do mahashaktiyan mili hain, charo taraf khusi ...   
10  hasoc_hi_1637  Chants of 'Jai Sri Ram' as Owaisi takes oath: ...   
11  hasoc_hi_5771  नृत्य होगा..!  संगीत होगा..!  जीवन मे उत्सव हो...   
12   hasoc_hi_288  गाये के नाम पर जुल्म करने वालों तुम्हारी औकात ...   
13  hasoc_hi_1803  डॉ. मुखर्जी ने एक देश में दो विधान दो प्रधान औ...   
14  hasoc_hi_5900  धार्मिक पदों पर बैठे कुछ लोग अपने को भगवान समझ...   
15  hasoc_hi_5951  सिक्का मोहब्बत का उछाल रक्खा है ~  हाँ मगर खुद...   

    task_1_HOF  task_1_NOT  task_2_PRFN  task_3_TIN  task_3_UNT  \
1            0           1            0           0           0   
2            1           0            1           0           1   
3            1           0            1           1           0   
4            0           1            0           0           0   
5            0           1            0           0           0   
6            0           1            0           0           0   
7            0           1            0           0           0   
8            0           1            0           0           0   
9            0           1            0           0           0   
10           0           1            0           0           0   
11           0           1            0           0           0   
12           0           1            0           0           0   
13           0           1            0           0           0   
14           0           1            0           0           0   
15           0           1            0           0           0   

                                  text_code_mixed_0.1  \
1   Great comeback of Bangladesh, stopped India fo...   
2   सब लोग is busy watching Randi dance, as soon a...   
3   वहाँ है केवल ए कमी का shoes for bastards like ...   
4   बी जे पी MLA Akash Vijayvargiya released from ...   
5   Chamki fever: RJD's performance in the assembl...   
6   लोग are facing a lot of problems due to rain i...   
7   अहमद का dad:-- beta aaj teri mammy kyu nahi ba...   
8   5 लाख मुसलमानों come to Ajmer's Dargah in Urs,...   
9   वहाँ हैं great powers, there is happiness on a...   
10  मंत्र of 'Jai Sri Ram' as Owaisi takes oath: A...   
11  वहाँ इच्छा होना dance..! There will be music.....   
12  वे WHO वादा करना atrocities in the name of cow...   
13  डॉ। मुखर्जी लड़ा to end permit raj considering...   
14  कुछ लोग sitting on religious positions conside...   
15   सिक्का है kept the boom of love ~ yes but has...   

                                  text_code_mixed_0.3  \
1   महान वापस लौटें of Bangladesh, stopped India f...   
2   सब लोग है व्यस्त देख रहे Randi dance, as soon ...   
3   वहाँ है केवल ए कमी का जूते के लिए कमीनों पसंद ...   
4   बी जे पी विधायक आकाश Vijayvargiya मुक्त from j...   
5   Chamki बुखार: राजद के प्रदर्शन in the assembly...   
6   लोग हैं का सामना करना पड़ a lot of problems du...   
7   अहमद का पापा:-- बीटा aaj teri mammy kyu nahi b...   
8   5 लाख मुसलमानों आना को अजमेर का दरगाह में उर्स...   
9   वहाँ हैं महान शक्तियां, वहाँ है ख़ुशी on all s...   
10  मंत्र का 'जय श्री Ram' as Owaisi takes oath: A...   
11  वहाँ इच्छा होना नृत्य..! वहाँ इच्छा होना संगीत...   
12  वे WHO वादा करना अत्याचार में  नाम का गाय, you...   
13  डॉ। मुखर्जी लड़ा को अंत आज्ञा देना राज मानते ह...   
14  कुछ लोग बैठक पर धार्मिक पदों विचार करना themse...   
15   सिक्का है र

In [ ]:
# Sections of config

# Defining some key variables that will be used later on in the training
MAX_LEN = 200
TRAIN_BATCH_SIZE = 8
VALID_BATCH_SIZE = 4
EPOCHS = 6
LEARNING_RATE = 1e-05
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

loading file vocab.txt from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/a265f773a47193eed794233aa2a0f0bb6d3eaa63/vocab.txt
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/a265f773a47193eed794233aa2a0f0bb6d3eaa63/tokenizer_config.json


loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/a265f773a47193eed794233aa2a0f0bb6d3eaa63/config.json
Model config BertConfig {
  "_name_or_path": "bert-base-uncased",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.29.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [ ]:
class CustomDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_len):
        self.tokenizer = tokenizer
        self.data = dataframe
        self.comment_text = dataframe.comment_text
        self.targets = self.data.list
        self.max_len = max_len

    def __len__(self):
        return len(self.comment_text)

    def __getitem__(self, index):
        comment_text = str(self.comment_text[index])
        comment_text = " ".join(comment_text.split())

        inputs = self.tokenizer.encode_plus(
            comment_text,
            None,
            add_special_tokens=True,
            max_length=self.max_len,
            pad_to_max_length=True,
            return_token_type_ids=True
        )
        ids = inputs['input_ids']
        mask = inputs['attention_mask']
        token_type_ids = inputs["token_type_ids"]


        return {
            'ids': torch.tensor(ids, dtype=torch.long),
            'mask': torch.tensor(mask, dtype=torch.long),
            'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),
            'targets': torch.tensor(self.targets[index], dtype=torch.float)
        }


In [ ]:
class CustomDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_len):
        self.tokenizer = tokenizer
        self.data = dataframe
        self.comment_text = dataframe.comment_text
        self.targets = self.data.list
        self.max_len = max_len

    def __len__(self):
        return len(self.comment_text)

    def __getitem__(self, index):
        comment_text = str(self.comment_text[index])
        comment_text = " ".join(comment_text.split())

        inputs = self.tokenizer.encode_plus(
            comment_text,
            None,
            add_special_tokens=True,
            max_length=self.max_len,
            pad_to_max_length=True,
            return_token_type_ids=True
        )
        ids = inputs['input_ids']
        mask = inputs['attention_mask']
        token_type_ids = inputs["token_type_ids"]


        return {
            'ids': torch.tensor(ids, dtype=torch.long),
            'mask': torch.tensor(mask, dtype=torch.long),
            'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),
            'targets': torch.tensor(self.targets[index], dtype=torch.float)
        }


In [ ]:
new_df = df[['comment_text', 'list']].copy()
new_df.head()

comment_text             list
1  बांग्लादेश की शानदार वापसी, भारत को 314 रन पर ...  [0, 1, 0, 0, 0]
2  सब रंडी नाच देखने मे व्यस्त जैसे ही कोई  के सा...  [1, 0, 1, 0, 1]
3  तुम जैसे हरामियों के लिए बस जूतों की कमी है शु...  [1, 0, 1, 1, 0]
4  बीजेपी MLA आकाश विजयवर्गीय जेल से रिहा, जमानत ...  [0, 1, 0, 0, 0]
5  चमकी बुखार: विधानसभा परिसर में आरजेडी का प्रदर...  [0, 1, 0, 0, 0]

In [ ]:
new_df_0_1 = df[['text_code_mixed_0.1', 'list']].copy()
#new_df.head()
new_df_0_1.rename(columns = {'text_code_mixed_0.1':'comment_text'}, inplace = True)
new_df_0_1.head()

comment_text             list
1  Great comeback of Bangladesh, stopped India fo...  [0, 1, 0, 0, 0]
2  सब लोग is busy watching Randi dance, as soon a...  [1, 0, 1, 0, 1]
3  वहाँ है केवल ए कमी का shoes for bastards like ...  [1, 0, 1, 1, 0]
4  बी जे पी MLA Akash Vijayvargiya released from ...  [0, 1, 0, 0, 0]
5  Chamki fever: RJD's performance in the assembl...  [0, 1, 0, 0, 0]

In [ ]:
# Creating the dataset and dataloader for the neural network

train_size = 0.8
train_dataset=new_df_0_1.sample(frac=train_size,random_state=200)
test_dataset=new_df_0_1.drop(train_dataset.index).reset_index(drop=True)
train_dataset = train_dataset.reset_index(drop=True)


print("FULL Dataset: {}".format(new_df_0_1.shape))
print("TRAIN Dataset: {}".format(train_dataset.shape))
print("TEST Dataset: {}".format(test_dataset.shape))

training_set = CustomDataset(train_dataset, tokenizer, MAX_LEN)
testing_set = CustomDataset(test_dataset, tokenizer, MAX_LEN)

FULL Dataset: (15, 2)
TRAIN Dataset: (12, 2)
TEST Dataset: (3, 2)


In [ ]:
train_params = {'batch_size': TRAIN_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 0
                }

test_params = {'batch_size': VALID_BATCH_SIZE,
                'shuffle': True,
                'num_workers': 0
                }

training_loader = DataLoader(training_set, **train_params)
testing_loader = DataLoader(testing_set, **test_params)


In [ ]:
# Creating the customized model, by adding a drop out and a dense layer on top of distil bert to get the final output for the model. 

class BERTClass(torch.nn.Module):
    def __init__(self):
        super(BERTClass, self).__init__()
        self.l1 = transformers.BertModel.from_pretrained('bert-base-uncased',return_dict=False)
        
        self.l2 = torch.nn.Dropout(0.3)
        self.l3 = torch.nn.Linear(768, 5)
    
    def forward(self, ids, mask, token_type_ids):
        _, output_1= self.l1(ids, attention_mask = mask, token_type_ids = token_type_ids)
        output_2 = self.l2(output_1)
        output = self.l3(output_2)
        return output

model = BERTClass()
model.to(device)

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/a265f773a47193eed794233aa2a0f0bb6d3eaa63/config.json
Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "return_dict": false,
  "transformers_version": "4.29.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--bert-base-uncased/snapshots/a265f773a47193eed794233aa2a0f0bb6d3eaa63/pytorch_model.bin
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceC

BERTClass(
  (l1): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tr

In [ ]:
def loss_fn(outputs, targets):
    return torch.nn.BCEWithLogitsLoss()(outputs, targets)

In [ ]:
optimizer = torch.optim.Adam(params =  model.parameters(), lr=LEARNING_RATE)

In [ ]:
def train(epoch):
    model.train()
    for _,data in enumerate(training_loader, 0):
        ids = data['ids'].to(device, dtype = torch.long)
        mask = data['mask'].to(device, dtype = torch.long)
        token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
        targets = data['targets'].to(device, dtype = torch.float)

        outputs = model(ids, mask, token_type_ids)

        optimizer.zero_grad()
        loss = loss_fn(outputs, targets)
        if _%5000==0:
            print(f'Epoch: {epoch}, Loss:  {loss.item()}')
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


In [ ]:
for epoch in range(EPOCHS):
    train(epoch)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:2364: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


Epoch: 0, Loss:  0.6687054634094238


In [ ]:
def validation(epoch):
    model.eval()
    fin_targets=[]
    fin_outputs=[]
    with torch.no_grad():
        for _, data in enumerate(testing_loader, 0):
            ids = data['ids'].to(device, dtype = torch.long)
            mask = data['mask'].to(device, dtype = torch.long)
            token_type_ids = data['token_type_ids'].to(device, dtype = torch.long)
            targets = data['targets'].to(device, dtype = torch.float)
            outputs = model(ids, mask, token_type_ids)
            fin_targets.extend(targets.cpu().detach().numpy().tolist())
            fin_outputs.extend(torch.sigmoid(outputs).cpu().detach().numpy().tolist())
    return fin_outputs, fin_targets


In [ ]:
for epoch in range(EPOCHS):
    outputs, targets = validation(epoch)
    outputs = np.array(outputs) >= 0.5
    accuracy = metrics.accuracy_score(targets, outputs)
    f1_score_micro = metrics.f1_score(targets, outputs, average='micro')
    f1_score_macro = metrics.f1_score(targets, outputs, average='macro')
    print(f"Accuracy Score = {accuracy}")
    print(f"F1 Score (Micro) = {f1_score_micro}")
    print(f"F1 Score (Macro) = {f1_score_macro}")


Accuracy Score = 0.0
F1 Score (Micro) = 0.5
F1 Score (Macro) = 0.2


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
